#开发环境配置
server:
  port: 80
  context-path: /
spring:
  application:
    name: unifiedLogin
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/unifiedlogin?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 970389
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  freemarker:
    charset: UTF-8
    cache: false
    content-type: text/html
    check-template-location: true
    expose-request-attributes: true
    expose-session-attributes: true
    suffix: .html #指定文件后缀
    template-loader-path: classpath:/templates/ #默认
#eureka:
#  client:
#    service-url:
#      defaultZone: http://server1:1111/eureka/,http://server2:1112/eureka/,http://server3:1113/eureka/
#  instance:
#    hostname: localhost
#    lease-expiration-duration-in-seconds: 90
#    lease-renewal-interval-in-seconds: 30
#自定义配置
account:
  username: zuma
  password: 123456
